name: CampFireDemo
version: ${project.version}
main: com.hiddentech.campfiredemo.CampFireDemo
api-version: 1.16
depend: [Grid]
authors: [hidden1nin]
description: Makes campfires give healing and demos gridutil
